# Generated by Django 4.2.8 on 2024-03-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='is_phone_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='is_telegram_verified',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
